#!/usr/bin/env python3

import numpy as np
import geopy
import geopy.distance as gd
import scipy.interpolate as si

def pol2cart(theta, rho):
    """
    A simple function to convert from polar to cartesian (x,y) coordinates, in
    the style of MATLAB `pol2cart` function.

    Parameters
    ----------
    theta : int or float
        Theta coordinates (in radians) on polar coordinate grid.
    rho : int or float
        Rho coordinates (between 0 and 1) on polar coordinate grid.

    Returns
    -------
    x, y : ndarrays
        Arrays of Cartesian coordinates (x & y) corresponding to input polar
        coordinates.
    """

    x = rho * np.cos(theta)
    y = rho * np.sin(theta)
    return(x,y)

def radial_grid(start_radius, radius_step, end_radius, degree_resolution):
    """
    A function to define a radial interpolation grid based on a unit circle,
    and centered on a geographic (lat, lon) point of interest. This methodology
    was developed by Loikith & Broccoli 2012* and was originally written in
    MATLAB. This Python implementation was developed as part of my M.S. thesis
    at Portland State University.

    -Dmitri Kalashnikov (dmitrik1357@gmail.com)

    * Loikith, P. C., and A. J. Broccoli, 2012: Characteristics of Observed
      Atmospheric Circulation Patterns Associated with Temperature Extremes
      over North America. J. Climate, 25, 7266–7281,
      https://doi.org/10.1175/JCLI-D-11-00709.1

    Parameters
    ----------
    start_radius : int or float
        Radius distance in km (from origin) of first (innermost)
        interpolation ring. If `start_radius` = 0, interpolation at
        origin and at 0 degree azimuth will be duplicated in order
        to produce a continuous contourf plot for visualization. If
        `start_radius` is set to any value higher than zero, both the
        origin and 0 degree azimuth will be interpolated only once.
        Use this version if computing statistics as all
        interpolation points will be unique. Use version with
        `start_radius` = 0 for plotting, as otherwise the plot will
        show no values around center and no values in a vertical
        slice at 0 degrees from center.
    radius_step : int or float
        Radius distance in km between each interpolation ring. When
        `start_radius` != 0, `radius_step` will be equal to `start_radius`.
    end_radius : int or float
        Radius distance in km (from origin) of last (outermost)
        interpolation ring; this distance defines the radius of the
        full circle and the outer edge of interpolated values relative
        to the origin latitude/longitude point (e.g. 2500 km).
    degree_resolution : int or float
        Spacing, in degrees, between each interpolation point
        on unit circle. For example, specifying a value of 1
        will yield 360 interpolation points on each
        interpolation ring, one point for each degree increment.

    Returns
    -------
    radius_steps, degree_steps : ndarrays
        Vectors of polar coordinates (kilometers, degrees) defining the
        radial interpolation grid in geographic space.
    """

    assert start_radius >= 0, "Radius values must not be negative"
    assert radius_step < (end_radius - start_radius),"""
Radius steps must be less than full radius"""
    assert 0 < degree_resolution <= 90,"""
Degree resolution should be positive value not exceeding 90"""

    # If start_radius is set to zero, will duplicate interpolation of origin
    # and 0-degree (360-degree) azimuth. This is done to create smooth contourf
    # plot for visualization.
    if start_radius == 0:
        radius_steps = np.arange(start_radius,end_radius+1,radius_step)
        degree_steps = np.arange(0,361,degree_resolution)

    # Version without duplication, for computing statistics.
    else:
        radius_steps = np.arange(start_radius,end_radius+1,radius_step)
        degree_steps = np.arange(0+degree_resolution,361,degree_resolution)

    return radius_steps, degree_steps

def radial_interp(a, a_lats, a_lons, center_lat, center_lon, radius_steps,
                  degree_steps, return_coordinates=False):
    """
    A function to interpolate continuous, geographic data using a unit circle
    centered on a geographic (lat, lon) point of interest. This methodology was
    developed by Loikith & Broccoli 2012* and was originally written in MATLAB.
    This Python implementation was developed as part of my M.S. thesis at
    Portland State University.

    -Dmitri Kalashnikov (dmitrik1357@gmail.com)

    * Loikith, P. C., and A. J. Broccoli, 2012: Characteristics of Observed
      Atmospheric Circulation Patterns Associated with Temperature Extremes
      over North America. J. Climate, 25, 7266–7281,
      https://doi.org/10.1175/JCLI-D-11-00709.1

    Parameters
    ----------
    a : ndarray
        2D or 3D input array of values from which to interpolate (data should
        be spatial and continuous on a regular grid, e.g. raster, reanalysis,
        climate model output, etc); with 3rd dimension representing time.
    a_lats : int or float
        Vector of latitude values defining input data array.
    a_lons : int or float
        Vector of longitude values defining input data array.
    center_lat : int or float
        Latitude coordinate of origin, around which the unit circle
        interpolator will be built.
    center_lon : int or float
        Longitude coordinate of origin, around which the unit circle
        interpolator will be built.
    radius_steps : int or float
        Distance (km) between interpolation rings.
    degree_steps : int or float
        Azimuth resolution (degrees) between interpolation
        points on each interpolation ring.
    return_coordinates : True, optional
        Boolean to indicate whether lat & lon interpolation
        coordinates should be returned, default is "False" for
        Matplotlib.pyplot contourf plotting. Set to "True" if mapping on
        geographically projected axes.

    Returns
    -------
    interp_vals : ndarray
        For 2D input array: returns vector of interpolated values
        extracted from input array at every (lat,lon) point on radial grid.
        For 3D input arrary: returns 2D array of (interpolated values,
        timesteps).
    interp_lat : ndarray
        The latitude coordinates of interpolated points.
    interp_lon : ndarray
        The longitude coordinates of interpolated points.
    """

    assert 2 <= a.ndim <= 3, "Input array must be 2D or 3D"
    assert radius_steps[0] >= 0, "Starting radius must not be negative"

    if np.size(center_lat) != 1:
        raise ValueError("Must provide single value for latitude")
    if np.size(center_lon) != 1:
        raise ValueError("Must provide single value for longitude")

    interp_lat = []
    interp_lon = []

    for km in radius_steps:
        for deg in degree_steps:
            start = geopy.Point(center_lat,center_lon)
            transect = gd.distance(kilometers = km)
            dest = transect.destination(point = start, bearing = deg)
            interp_lat.append(dest[0])
            interp_lon.append(dest[1])

    if radius_steps[0] != 0:
        # Add lat & lon of origin
        interp_lat = np.hstack([center_lat, interp_lat])
        interp_lon = np.hstack([center_lon, interp_lon])

    interp_vals = si.interpn((a_lons,a_lats),a,(interp_lon,interp_lat))

    # For mapping on geographic projection, can use the interpolated (lat,
    # lon) values
    if return_coordinates == True:
        return interp_vals, interp_lat, interp_lon
    # For non-projected contourf plot, lat & lon values will not be needed
    else:
        return interp_vals

def create_mappable(radius_steps, degree_steps, interp_vals):
    """
    A function to create mappable inputs to contourf plot, for visualizing data
    obtained from radial interpolation.

    Parameters
    ----------
    radius_steps : ndarray
        Distance (km) between interpolation rings on unit circle
        interpolator.
    degree_steps : ndarray
        Azimuth resolution (degrees) between interpolation points on unit
        circle interpolator.
    interp_vals : ndarray
        Interpolated values corresponding to above (km, deg) coordinates.

    Returns
    -------
    x, y : ndarrays
        Cartesian coordinates on unit circle, corresponding to (km, deg)
        coordinates obtained from radial interpolation.
    array : ndarray
        Interpolated values corresponding to Cartesian (x,y) coordinates above
        for contourf plotting.
    """

    assert interp_vals.ndim == 1, "Input data values must be 1D"
    assert radius_steps[0] == 0, """
Starting radius must be zero for contourf mappable"""

    rho = radius_steps/radius_steps[-1] # radius values on unit circle (r = 1)
    theta = np.deg2rad(degree_steps) # convert to radians
    array = np.reshape(interp_vals,(len(radius_steps),len(degree_steps))) # reshape to match coordinates
    (th, rh) = np.meshgrid(theta, rho) # create meshgrid on polar coordinates
    (x, y) = pol2cart(th, rh) # convert meshgrid to cartesian (x,y) coordinates

    # Return 3 vectors - the array values, the x-coordinates, and the
    # y-coordinates for input into contourf plot.
    return array, x, y
